-- MySQL Script generated by MySQL Workbench
-- 09/29/16 11:10:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospital` ;

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`TipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`TipoDocumento` ;

CREATE TABLE IF NOT EXISTS `hospital`.`TipoDocumento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`EstadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`EstadoCivil` ;

CREATE TABLE IF NOT EXISTS `hospital`.`EstadoCivil` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`NivelEducativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`NivelEducativo` ;

CREATE TABLE IF NOT EXISTS `hospital`.`NivelEducativo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Madre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Madre` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Madre` (
  `ID` INT(45) NOT NULL,
  `DPI` INT NOT NULL,
  `RFID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `PrimerApellido` VARCHAR(45) NULL,
  `SegundoApellido` VARCHAR(45) NULL,
  `FechaDeNacimiento` DATE NULL,
  `Edad` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `TipoDeOcupacion` VARCHAR(45) NULL,
  `TotalDeEmbarazos` INT NULL,
  `HijosActualmenteVivos` INT NULL,
  `HijosNacidosVivosQueFallecieron` INT NULL,
  `AbortosONacidosMuertos` INT NULL,
  `FechaNacimientoUltimoHijo` DATE NULL,
  `TipoDocumento` INT NOT NULL,
  `EstadoCivil` INT NOT NULL,
  `NivelEducativo` INT NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`, `DPI`, `RFID`, `TipoDocumento`, `EstadoCivil`, `NivelEducativo`),
  INDEX `fk_Madre_TipoDocumento1_idx` (`TipoDocumento` ASC),
  INDEX `fk_Madre_EstadoCivil1_idx` (`EstadoCivil` ASC),
  INDEX `fk_Madre_NivelEducativo1_idx` (`NivelEducativo` ASC),
  CONSTRAINT `fk_Madre_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento`)
    REFERENCES `hospital`.`TipoDocumento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Madre_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil`)
    REFERENCES `hospital`.`EstadoCivil` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Madre_NivelEducativo1`
    FOREIGN KEY (`NivelEducativo`)
    REFERENCES `hospital`.`NivelEducativo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Sede` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Sede` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(45) NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`AtendioParto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`AtendioParto` ;

CREATE TABLE IF NOT EXISTS `hospital`.`AtendioParto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CondicionParto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`CondicionParto` ;

CREATE TABLE IF NOT EXISTS `hospital`.`CondicionParto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`TipoParto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`TipoParto` ;

CREATE TABLE IF NOT EXISTS `hospital`.`TipoParto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Neonato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Neonato` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Neonato` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RFID` INT NOT NULL,
  `Genero` VARCHAR(45) NULL,
  `Peso` FLOAT NULL,
  `Talla` FLOAT NULL,
  `PerimetroCefalico` FLOAT NULL,
  `PerimetroToracico` FLOAT NULL,
  `HoraDeNacimiento` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `DuracionDelEmbarazo` VARCHAR(45) NULL,
  `MalformacionCongenita` VARCHAR(45) NULL,
  `LactanciaPrecoz` VARCHAR(45) NULL,
  `TipoDeLigaduraYCorteDelCordon` VARCHAR(45) NULL,
  `Sede` INT NOT NULL,
  `AtendioParto` INT NOT NULL,
  `CondicionParto` INT NOT NULL,
  `TipoParto` INT NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`, `RFID`, `Sede`, `AtendioParto`, `CondicionParto`, `TipoParto`),
  INDEX `fk_Neonato_Sede1_idx` (`Sede` ASC),
  INDEX `fk_Neonato_AtendioParto1_idx` (`AtendioParto` ASC),
  INDEX `fk_Neonato_CondicionParto1_idx` (`CondicionParto` ASC),
  INDEX `fk_Neonato_TipoParto1_idx` (`TipoParto` ASC),
  CONSTRAINT `fk_Neonato_Sede1`
    FOREIGN KEY (`Sede`)
    REFERENCES `hospital`.`Sede` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Neonato_AtendioParto1`
    FOREIGN KEY (`AtendioParto`)
    REFERENCES `hospital`.`AtendioParto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Neonato_CondicionParto1`
    FOREIGN KEY (`CondicionParto`)
    REFERENCES `hospital`.`CondicionParto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Neonato_TipoParto1`
    FOREIGN KEY (`TipoParto`)
    REFERENCES `hospital`.`TipoParto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Profesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Profesion` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Profesion` (
  `ID` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Profecional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Profecional` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Profecional` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NoColegiatura` INT NOT NULL,
  `DPI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `PrimerApellido` VARCHAR(45) NULL,
  `SegundoApellido` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `CertificaDeclara` VARCHAR(45) NULL,
  `TipoDocumento` INT NOT NULL,
  `Sede` INT NOT NULL,
  `Profesion` INT NOT NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`, `NoColegiatura`, `DPI`, `TipoDocumento`, `Sede`, `Profesion`),
  INDEX `fk_Profecional_TipoDocumento1_idx` (`TipoDocumento` ASC),
  INDEX `fk_Profecional_Sede1_idx` (`Sede` ASC),
  INDEX `fk_Profecional_Profesion1_idx` (`Profesion` ASC),
  CONSTRAINT `fk_Profecional_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento`)
    REFERENCES `hospital`.`TipoDocumento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profecional_Sede1`
    FOREIGN KEY (`Sede`)
    REFERENCES `hospital`.`Sede` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profecional_Profesion1`
    FOREIGN KEY (`Profesion`)
    REFERENCES `hospital`.`Profesion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`Role` ;

CREATE TABLE IF NOT EXISTS `hospital`.`Role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Activo` BIT NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`UserRole` ;

CREATE TABLE IF NOT EXISTS `hospital`.`UserRole` (
  `Usuario_ID` INT NOT NULL,
  `Role_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Role_ID`),
  INDEX `fk_Usuario_has_Role_Role1_idx` (`Role_ID` ASC),
  INDEX `fk_Usuario_has_Role_Usuario_idx` (`Usuario_ID` ASC),
  CONSTRAINT `fk_Usuario_has_Role_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `hospital`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Role_Role1`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `hospital`.`Role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `hospital` ;

-- -----------------------------------------------------
-- Placeholder table for view `hospital`.`CertificadoNacimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CertificadoNacimiento` (`DPIMadre` INT, `NombreMadre` INT, `PrimerApellidoMadre` INT, `SegundoApellidoMadre` INT, `EdadMadre` INT, `DireccionMadre` INT, `GeneroNeonato` INT, `FechaNacimientoNeonato` INT, `SedeNeonato` INT, `HoraDeNacimientoNeonato` INT, `TipoDocumentoProfecional` INT, `PrimerApellidoProfecional` INT, `SegundoApellidoProfecional` INT, `NombreProfecional` INT, `DPIProfecional` INT, `CertificaDeclaraProfecional` INT, `SedeProfecional` INT, `NoColegiaturaProfecional` INT);

-- -----------------------------------------------------
-- View `hospital`.`CertificadoNacimiento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `hospital`.`CertificadoNacimiento` ;
DROP TABLE IF EXISTS `hospital`.`CertificadoNacimiento`;
USE `hospital`;
CREATE  OR REPLACE VIEW CertificadoNacimiento AS
    SELECT 
        madre.DPI AS DPIMadre,
        madre.Nombre AS NombreMadre,
        madre.PrimerApellido AS PrimerApellidoMadre ,
        madre.SegundoApellido AS SegundoApellidoMadre,
        madre.Edad AS EdadMadre,
        madre.Direccion AS DireccionMadre ,
        neonato.Genero AS GeneroNeonato ,
        neonato.FechaNacimiento AS FechaNacimientoNeonato ,
        neonato.Sede AS SedeNeonato ,
        neonato.HoraDeNacimiento AS HoraDeNacimientoNeonato ,
        profecional.TipoDocumento AS TipoDocumentoProfecional ,
        profecional.PrimerApellido AS PrimerApellidoProfecional ,
        profecional.SegundoApellido AS SegundoApellidoProfecional ,
        profecional.Nombre AS NombreProfecional ,
        profecional.DPI AS DPIProfecional ,
        profecional.CertificaDeclara AS CertificaDeclaraProfecional ,
        profecional.Sede AS SedeProfecional ,
        profecional.NoColegiatura AS NoColegiaturaProfecional
    FROM
        madre,
        neonato,
        profecional;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hospital`.`TipoDocumento`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`TipoDocumento` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'DPI', NULL, NULL);
INSERT INTO `hospital`.`TipoDocumento` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'CEDULA', NULL, NULL);
INSERT INTO `hospital`.`TipoDocumento` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'PASAPORTE', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`EstadoCivil`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`EstadoCivil` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'SOLTERO(A)', NULL, NULL);
INSERT INTO `hospital`.`EstadoCivil` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'CASADO(A)', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`NivelEducativo`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`NivelEducativo` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'PRIMARIA', NULL, NULL);
INSERT INTO `hospital`.`NivelEducativo` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'EDUCACION BASICA', NULL, NULL);
INSERT INTO `hospital`.`NivelEducativo` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'DIVERSIFICADO', NULL, NULL);
INSERT INTO `hospital`.`NivelEducativo` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (4, 'CARRERA UNIVERSITARIA', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`Madre`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`Madre` (`ID`, `DPI`, `RFID`, `Nombre`, `PrimerApellido`, `SegundoApellido`, `FechaDeNacimiento`, `Edad`, `Direccion`, `TipoDeOcupacion`, `TotalDeEmbarazos`, `HijosActualmenteVivos`, `HijosNacidosVivosQueFallecieron`, `AbortosONacidosMuertos`, `FechaNacimientoUltimoHijo`, `TipoDocumento`, `EstadoCivil`, `NivelEducativo`, `Activo`, `Timestamp`) VALUES (1, 2521134110114, 20160929, 'Jasmin', 'Cardona', NULL, '08-07-1996', 20, 'villa nueva', 'secretaria', 0, 0, 0, 0, NULL, 1, 1, 4, q, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`Sede`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`Sede` (`ID`, `Nombre`, `Direccion`, `Departamento`, `Municipio`, `Zona`, `Activo`, `Timestamp`) VALUES (1, 'HOSPITAL DE AMATITLAN', '4TA CALLE 10 AVE BARRIO HOSPITAL AMATITLAN', 'GUATEMALA', 'AMATITLAN', '0', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`AtendioParto`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`AtendioParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'ENFERMERO(A)', NULL, NULL);
INSERT INTO `hospital`.`AtendioParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'MEDICO GENERAL', NULL, NULL);
INSERT INTO `hospital`.`AtendioParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'MEDICO GINECO-OBSTETRA', NULL, NULL);
INSERT INTO `hospital`.`AtendioParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (4, 'OBSTETRA', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`CondicionParto`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`CondicionParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'ESPONTANEO', NULL, NULL);
INSERT INTO `hospital`.`CondicionParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'INSTRUMENTADO', NULL, NULL);
INSERT INTO `hospital`.`CondicionParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'CESAREA', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`TipoParto`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`TipoParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'UNICO', NULL, NULL);
INSERT INTO `hospital`.`TipoParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'DOBLE', NULL, NULL);
INSERT INTO `hospital`.`TipoParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'TRIPLE', NULL, NULL);
INSERT INTO `hospital`.`TipoParto` (`ID`, `Descripcion`, `Activo`, `Timestamp`) VALUES (4, 'MAS DE TRES', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`Neonato`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`Neonato` (`ID`, `RFID`, `Genero`, `Peso`, `Talla`, `PerimetroCefalico`, `PerimetroToracico`, `HoraDeNacimiento`, `FechaNacimiento`, `DuracionDelEmbarazo`, `MalformacionCongenita`, `LactanciaPrecoz`, `TipoDeLigaduraYCorteDelCordon`, `Sede`, `AtendioParto`, `CondicionParto`, `TipoParto`, `Activo`, `Timestamp`) VALUES (1, 20160929, '1', 500, 10, 10, 10, '10:26:00', '29-09-2016', '38', 'no', 'si', NULL, 1, 1, 1, 1, 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hospital`.`Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `hospital`;
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (1, 'DOCTOR', NULL, NULL, NULL);
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (2, 'ENFERMERO', 'DEBE LLENAR SOLO FORMULARIOS', NULL, NULL);
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (3, 'DIRECTOR', '', NULL, NULL);
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (4, 'ADMIN', NULL, NULL, NULL);
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (5, 'DBA', NULL, NULL, NULL);
INSERT INTO `hospital`.`Role` (`ID`, `Role`, `Descripcion`, `Activo`, `Timestamp`) VALUES (DEFAULT, '', NULL, NULL, NULL);

COMMIT;

